/**
 * @author Willie Ausrotas <wausrotas@gmail.com>
 *
 */
// Complete class Time12 adding add1Hour(), remove1Hour()
// add1Minute(), remove1Minute(), add1Second(), remove1Second()
class Time24 {
	// toString,equals and hashCode as generated by eclipse
	/* omitted */
	final int seconds;
	final int minutes;
	final int hours;

	Time24(int seconds, int minutes, int hours) {
		this.seconds = limit60(seconds);
		this.minutes = limit60(minutes);
		this.hours = limitHours(hours);
	}

	private static int limit60(int v) {// 0..59 ok
		if (v < 0 || v > 59) {
			throw new IllegalArgumentException("limit60 over " + v);
		}
		return v;
	}

	private static int limitHours(int v) {// 1..12 ok
		if (v < 0 || v > 23) {
			throw new IllegalArgumentException("limitHours over " + v);
		}
		return v;
	}

	static final Time24 twelve = new Time24(0, 0, 12);
	
	public Time24 add1Hour()
	{
		return new Time24(this.seconds,this.minutes,this.hours+1);
	}
	
	public Time24 remove1Hour()
	{
		if(this.hours > 0)
		{
			return new Time24(this.seconds,this.minutes,this.hours-1);
		}
		else
		{
			throw new IllegalArgumentException("Hours is already at 0.");
		}
	}
	
	public Time24 add1Minute()
	{
		if(this.minutes < 59)
		{
			return new Time24(this.seconds,this.minutes+1,this.hours);
		}
		else
		{
			return new Time24(this.seconds,0,this.hours+1);
		}
	}
	
	public Time24 remove1Minute()
	{
		if(this.minutes > 0)
		{
			return new Time24(this.seconds,this.minutes+1,this.hours);
		}
		else
		{
			return new Time24(this.seconds,0,this.hours-1);
		}
	}
	
	public Time24 add1Second()
	{
		if(this.seconds < 59)
		{
			return new Time24(this.seconds+1,this.minutes,this.hours);
		}
		else
		{
			return new Time24(0,this.minutes+1,this.hours);
		}
	}
	
	public Time24 remove1Second()
	{
		if(this.seconds > 0)
		{
			return new Time24(this.seconds-1,this.minutes,this.hours);
		}
		else
		{
			return new Time24(0,this.minutes-1,this.hours);
		}
	}
	

	public static void main(String[] arg) {
		/* omitted */
	}
}